### ISSUE TITLE
Maybe unsound in current_opcode

### ISSUE THREAD

**Issue by lwz23** [bnb-chain/revm#89]
hello, thank you for your contribution in this project, I am scanning the unsoundness problem in rust project.
I notice the following code:
```
pub struct Interpreter {
    /// The current instruction pointer.
    pub instruction_pointer: *const u8,
   .......................................

}
impl Interpreter {
............................
pub fn current_opcode(&self) -> u8 {
        unsafe { *self.instruction_pointer }
    }
......................
}
```
Considering that `instruction_pointer` is a `pub` field, I assume that users can directly manipulate this field. This potential situation could result in `self.instruction_pointer` being a null pointer, and directly dereferencing it might trigger undefined behavior (UB). For safety reasons, I felt it necessary to report this issue. If you have performed checks elsewhere that ensure this is safe, please don’t take offense at my raising this issue.

I think this is same problem with https://github.com/bluealloy/revm/issues/1902

**Comment by j75689** [comment]
Thank you for your report. It has been fixed based on the upstream version and we will bring it in the next version.
